version: '3.1'

services:
  mysql-master:
    build:
      context: .
      dockerfile: Dockerfile.master
    container_name: mysql-master2
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./master-data:/var/lib/mysql

  # mysql-slave:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.slave
  #   container_name: mysql-slave2
  #   restart: always
  #   ports:
  #     - "3308:3306"
  #   volumes:
  #     - ./slave-data:/var/lib/mysql
