FROM mysql:5.7

ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mydb

COPY ./master-init /docker-entrypoint-initdb.d
COPY ./init.sql /docker-entrypoint-initdb.d/init.sql

CMD ["mysqld", "--server-id=1", "--log-bin=mysql-bin", "--binlog-ignore-db=mysql"]
