FROM mysql:5.7

ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=mydb

COPY ./init.sql /docker-entrypoint-initdb.d/init.sql

CMD ["mysqld", "--server-id=2", "--relay-log=mysql-relay-bin", "--log-bin=mysql-bin", "--read-only=1"]
